### ISSUE TITLE
Travis build should just use requirements.txt

### ISSUE THREAD

**Issue by ssanderson** [quantopian/zipline#655]
We currently do a bizarre hodge-podge of conda installs and pip installs based on grepping from our requirements...
```
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi
  - sudo apt-get install gfortran
install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes -c https://conda.binstar.org/Quantopian numpy=$NUMPY_VERSION pandas=$PANDAS_VERSION scipy matplotlib Cython patsy statsmodels tornado pyparsing xlrd mock pytz requests six dateutil ta-lib logbook
  - grep cyordereddict== etc/requirements.txt | xargs pip install
  - grep contextlib2== etc/requirements.txt | xargs pip install
  - grep pyflakes== etc/requirements_dev.txt | xargs pip install
  - grep pep8== etc/requirements_dev.txt | xargs pip install
  - grep mccabe== etc/requirements_dev.txt | xargs pip install
  - grep flake8== etc/requirements_dev.txt | xargs pip install
  - grep nose== etc/requirements_dev.txt | xargs pip install --upgrade --force-reinstall
  - grep nose-parameterized== etc/requirements_dev.txt | xargs pip install
  - grep nose-ignore-docstring== etc/requirements_dev.txt | xargs pip install
  - pip install coveralls
  - pip install nose-timer
  - python setup.py build_ext --inplace
```

**Comment by ssanderson** [comment]
Oh, also, we're apparently `wget`ing a bash script over http and then executing it... :/

**Comment by twiecki** [comment]
The reason is that compiling numpy, scipy and pandas takes a long while increasing the wait time by a lot.

**Comment by ssanderson** [comment]
> The reason is that compiling numpy, scipy and pandas takes a long while increasing the wait time by a lot.

Gotcha.  I think a more maintainable solution would be to host wheels for the compile libraries.  I lost 5-6 hours this morning from having to add lines to the section where we're grepping things out of requirements.txt.  It's also worrying that we're testing on travis in a way that no one else is going to install zipline.  I'd rather have entirely separate conda and pip builds so that we have coverage for how people actually use the library.

**Comment by twiecki** [comment]
Agreed on all of those. I wonder if maybe someone else came up with a better solution to this. Not sure if the recent switch to docker on travis would help.

**Comment by peteut** [comment]
Recent `pip` version do cache wheels automatically, and it works great w/ Travis. 

[.travis.yml](https://github.com/peteut/zipline/blob/master/.travis.yml):
```
sudo: false
language: python
python:
  - 2.7
  - 3.3
cache:
  directories:
    - ${HOME}/.cache/pip
addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - libgmp-dev
      - libmpfr-dev
      - libsqlite3-dev
install:
  - pip install -U pip
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - export PREFIX="${HOME}"
  - export LIBPATH="${HOME}/lib"
  - export INCDIR="${HOME}/include"
  - tar xzf ta-lib-0.4.0-src.tar.gz
  - pushd ta-lib
  - ./configure --prefix="${PREFIX}" && make && make install
  - popd
  - export CFLAGS+="-Wl,-rpath,${LIBPATH} -I${LIBPATH}/include"
  - export TA_LIBRARY_PATH="${LIBPATH}"
  - export TA_INCLUDE_PATH="${INCDIR}"
  - pip install -U TA-lib
  - pip install -U nose-timer coverage
  - pip install -e .[dev]
  - pip install coveralls
before_script:
  - flake8 zipline tests
  - python setup.py build_ext --inplace
script:
  - nosetests --with-timer --exclude=^test_examples --with-coverage --cover-package=zipline
after_success:
  - coveralls
```
